using System.Text.Json.Serialization;

namespace CodingAgent.Core.Models.Orchestration;

/// <summary>
/// Enriched repository context with analyzed project information
/// Built by the ContextAgent step (LLM-powered exploration)
/// </summary>
public class EnrichedRepositoryContext
{
    /// <summary>
    /// Repository name
    /// </summary>
    [JsonPropertyName("name")]
    public string RepositoryName { get; set; } = string.Empty;

    /// <summary>
    /// Repository path (set from workspace context, not from LLM)
    /// </summary>
    [JsonIgnore]
    public string RepositoryPath { get; set; } = string.Empty;

    /// <summary>
    /// Total file count (set from workspace context, not from LLM)
    /// </summary>
    [JsonIgnore]
    public int TotalFiles { get; set; }

    /// <summary>
    /// Detected project type (C# / .NET, Python, JavaScript/TypeScript, etc.)
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("projectType")]
    public string ProjectType { get; set; } = string.Empty;

    /// <summary>
    /// Build system (dotnet, npm, maven, gradle, etc.)
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("buildSystem")]
    public string BuildSystem { get; set; } = string.Empty;

    /// <summary>
    /// Test project paths
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("testProjects")]
    public List<string> TestProjects { get; set; } = new();

    /// <summary>
    /// Source directories
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("sourceDirectories")]
    public List<string> SourceDirectories { get; set; } = new();

    /// <summary>
    /// Entry point files (Program.cs, main.py, index.js, etc.)
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("entryPoints")]
    public List<string> EntryPoints { get; set; } = new();

    /// <summary>
    /// Important file paths (solution files, package.json, etc.)
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("importantFiles")]
    public Dictionary<string, string> ImportantFiles { get; set; } = new();

    /// <summary>
    /// Major dependencies/frameworks used
    /// Discovered by LLM exploration
    /// </summary>
    [JsonPropertyName("dependencies")]
    public List<string> Dependencies { get; set; } = new();

    /// <summary>
    /// Pre-formatted context summary for planning agent
    /// Generated by LLM
    /// </summary>
    [JsonPropertyName("planningContextSummary")]
    public string PlanningContextSummary { get; set; } = string.Empty;

    /// <summary>
    /// Pre-formatted context summary for execution agent
    /// Generated by LLM
    /// </summary>
    [JsonPropertyName("executionContextSummary")]
    public string ExecutionContextSummary { get; set; } = string.Empty;

    /// <summary>
    /// Whether the repository has test projects
    /// </summary>
    [JsonIgnore]
    public bool HasTestProjects => TestProjects.Any();
}
